### ISSUE TITLE
hg38 mappability files

### ISSUE THREAD

**Issue by leraman** [broadinstitute/ichorCNA#22]
For anyone who's interested, I've created mappability tracks for hg38 at 500 kb and 1000 kb. Note that I added .txt extensions, otherwise git won't let me upload them.

[map_hg38_1000kb.wig.txt](https://github.com/broadinstitute/ichorCNA/files/1932429/map_hg38_1000kb.wig.txt)
[map_hg38_500kb.wig.txt](https://github.com/broadinstitute/ichorCNA/files/1932430/map_hg38_500kb.wig.txt)

**Comment by gavinha** [comment]
Hi @leraman 

Thanks for providing these files.  Definitely very useful for other users.

I've added these to [inst/extdata](https://github.com/broadinstitute/ichorCNA/tree/master/inst/extdata)

Best,
Gavin

**Comment by jaldrich** [comment]
Hi - 
I am running ichorCNA against build 38 with the gc and mappability files included in inst/extdata. We were noticing a drop in density across chromosomes (compared to running the same sample against hg19) and data for chr19 are completely missing. I think I narrowed it down to mappability file. Has anyone else encountered this issue? Do we need to generate our own mappability file? Even tho running it without the mappability files seems to work just fine too. 

Thank you,
Jessica

**Comment by gavinha** [comment]
Hi @jaldrich 

The mappability file is optional but if provided will help to filter out bins in regions of lower sequence uniqueness (i.e. lower mappability score). This tends to help with some localized noise in the data.

I am unsure why you are experiencing issues. What bin size are you using? How many total bins did you have with hg19 and now with hg38?
I am about to reanalyze data (for 1000kb or 1Mb bins) from our publication using hg38 so I'll let you if I can reproduce this.

I have analyzed other data for 10kb bins using `map_hg38_10kb.wig`, which I generated using the tool `gem-mappability` and it seems to be fine.

Best,
Gavin

**Comment by jaldrich** [comment]
Hi Gavin -

Thank you for your response! 

Sorry - I neglected to mention I am working with the 1Mb bin wig files. 
Here is the line count from the WIG:

>> wc -l map_hg38_1000kb.wig
>> 3126 map_hg38_1000kb.wig

And if I count for mappability < 0.9 which is what I think ichorCNA filters by default:

>> awk '$1 < 0.9' map_hg38_1000kb.wig |wc -l
>> 1715

Which is about 50% of the bins getting filtered. 

For build 37, its seems like only about 2% of bins would get filtered. 

I'm working on regenerating mappability wig file right now - I was just curious about building it with and without all the extra contigs in build 38 (ALT,etc). I'll let you know how that goes. 

Thank you!
Jessica

**Comment by wisekh6** [comment]
Hi Gavin,

The UCSC has two hg19 mappability BigWig files:
```
wgEncodeDukeMapabilityUniqueness20bp.bigWig
wgEncodeDukeMapabilityUniqueness35bp.bigWig 
```

Would you guide about which file is an input to the following `HMM Copy Utils` command?

```
Usage: ./mapCounter [options] <BigWig file>
```

Thanks in advance,
