### ISSUE TITLE
custom parameters for 30x WGS TitanCNA analysis

### ISSUE THREAD

**Issue by sbamin** [broadinstitute/ichorCNA#27]
Hi,

I am trying running TitanCNA snakemake workflow on 30X paired tumor/normal whole genomes. I see following parameters set for 0.1x genome and optional 1x genome. For 30x genome, would you have recommended parameters or suggestions that I can check and use in my trial runs. I am reading both, TitanCNA and ichoCNA manuscripts to get more idea on how to these parameters can be adjusted for WGS.

https://github.com/broadinstitute/ichorCNA/blob/92c8bd1e54a1221c55d590c27a91c994da62577a/scripts/runIchorCNA.R#L248-L279

Thanks,
Samir

**Comment by gavinha** [comment]
Hi @sbamin 

Those parameters are for copy number predictions using ichorCNA. For TitanCNA analysis, you only really need the normalized data prior to ichorCNA's copy number inference. Therefore, it doesn't matter what the parameters are here.

However, if you would like to use the ichorCNA results, then you can consider these parameters. For 30X WGS, TitanCNA will be the better analysis to perform.

Hope this helps.
Gavin
