### ISSUE TITLE
Creation of Mappability Files

### ISSUE THREAD

**Issue by mej54** [broadinstitute/ichorCNA#29]
Hi,

I'm wondering how the mappability wig files under inst/extdata were created?  I'm hoping to create these files with 1kb windows. 

Thanks in advance!

**Comment by gavinha** [comment]
Hi @mej54 

The instructions to create the GC content and mappability files are provided https://github.com/shahcompbio/hmmcopy_utils

For hg38, Bowtie doesn't work when trying to create mappability score files.  Others have been using gem-mappability tool for this.  I have recently added mappability (and GC) files for other bin sizes.  I can also include on for 1kb. 

Best,
Gavin

**Comment by gavinha** [comment]
This issue is resolved in #22
