### ISSUE TITLE
Panel of Normal Documentation Incomplete

### ISSUE THREAD

**Issue by rahulram70** [broadinstitute/ichorCNA#34]
Hey guys,

Could you please let me know what each parameter means for createPanelOfNormals.R? Thank you.

Rscript createPanelOfNormals.R 
    --filelist /path/to/wig_files.txt \
    --gcWig /path/to/gc.wig --mapWig /path/to/map.wig \
    --centromere /path/to/centromeres_file.txt \
    --outfile base_outfile_name

**Comment by gavinha** [comment]
Hi @rahulram70 

I updated the wiki with more information. Please let me know if you have any other questions or need more clarification.

Best,
Gavin
