### ISSUE TITLE
Which UCSC hg19 mappability BigWig file should be used for different bins?

### ISSUE THREAD

**Issue by wisekh6** [broadinstitute/ichorCNA#47]
Hi Gavin,

The UCSC has two hg19 mappability BigWig files:

wgEncodeDukeMapabilityUniqueness20bp.bigWig
wgEncodeDukeMapabilityUniqueness35bp.bigWig 
Would you guide about which file is an input to the following HMM Copy Utils command?

Usage: ./mapCounter [options] <BigWig file>
Thanks in advance,

**Comment by wisekh6** [comment]
Sorry. I just figured out. 
Thanks,

**Comment by lisajq** [comment]
@wisekh6 ,Hi, wisekh6 could you tell me which mer.bigWig file should be used?
