### ISSUE TITLE
Update release after bugfix?

### ISSUE THREAD

**Issue by mmterpstra** [broadinstitute/ichorCNA#48]
The github page has a release 0.1.0 but this is misleading when this is not updated. For example #8, #24 should warrant a new release. Please remove your releases or update them. 

Also please consider to add #33 (PR broadinstitute/ichorCNA#38) to the installation.

**Comment by jurhoades** [comment]
We've bumped the latest release to v0.2.0 and are working on getting #38 merged.

**Comment by mmterpstra** [comment]
Great! Thanks for the update!
