### ISSUE TITLE
Reference genome with the prefix 'chr'

### ISSUE THREAD

**Issue by joonlee3** [broadinstitute/ichorCNA#5]
Gavin,

   I took a look at some of the data sets in ichorCNA and found out that chromosome names are numeric (without the prefix 'chr')
   I am wondering if ichorCNA can deal with bam generated with hg19 with the prefix 'chr' 

   Please let me know.

Thanks,
Joon

**Comment by jurhoades** [comment]
Hi Joon,

You should be able to use BAM files with or without the "chr" contig prefix.  ichorCNA uses `GenomeInfoDb` R package to properly read common contig formats.  Let us know if you run into any trouble.

**Comment by joonlee3** [comment]
Thanks,

  As you suggested, I ran ichorCNA with the normal panel data provided in the 'extdata' by the 'ichorCNA' package. I've got the following error:

Parsing: fixedStep chrom=1 start=1 step=500000 span=500000
Parsing: fixedStep chrom=2 start=1 step=500000 span=500000
Parsing: fixedStep chrom=3 start=1 step=500000 span=500000
Parsing: fixedStep chrom=4 start=1 step=500000 span=500000
Parsing: fixedStep chrom=5 start=1 step=500000 span=500000
Parsing: fixedStep chrom=6 start=1 step=500000 span=500000
Parsing: fixedStep chrom=7 start=1 step=500000 span=500000
Parsing: fixedStep chrom=8 start=1 step=500000 span=500000
Parsing: fixedStep chrom=9 start=1 step=500000 span=500000
Parsing: fixedStep chrom=10 start=1 step=500000 span=500000
Parsing: fixedStep chrom=11 start=1 step=500000 span=500000
Parsing: fixedStep chrom=12 start=1 step=500000 span=500000
Parsing: fixedStep chrom=13 start=1 step=500000 span=500000
Parsing: fixedStep chrom=14 start=1 step=500000 span=500000
Parsing: fixedStep chrom=15 start=1 step=500000 span=500000
Parsing: fixedStep chrom=16 start=1 step=500000 span=500000
Parsing: fixedStep chrom=17 start=1 step=500000 span=500000
Parsing: fixedStep chrom=18 start=1 step=500000 span=500000
Parsing: fixedStep chrom=19 start=1 step=500000 span=500000
Parsing: fixedStep chrom=20 start=1 step=500000 span=500000
Parsing: fixedStep chrom=21 start=1 step=500000 span=500000
Parsing: fixedStep chrom=22 start=1 step=500000 span=500000
Parsing: fixedStep chrom=X start=1 step=500000 span=500000
Parsing: fixedStep chrom=Y start=1 step=500000 span=500000
Sorting by decreasing chromosome size
Correcting Tumour
Loading required package: GenomeInfoDb
Removed 163 bins near centromeres.
Applying filter on data...
Correcting for GC bias...
Correcting for mappability bias...
Filtering low uniqueness regions with mappability score < 0.9
Determining gender...Gender unknown
Error in `[[<-`(`*tmp*`, name, value = c(NA, -0.0448071293651577, NA,  : 
  5229 elements in value to replace 4987 elements
Calls: normalizeByPanelOrMatchedNormal -> $<- -> $<- -> [[<- -> [[<-
In addition: Warning messages:
1: In tumour_copy$copy - panel$Median :
  longer object length is not a multiple of shorter object length
Execution halted

FYI:
- Instead of using the normal panel data, I launched a test run with a pseudo-matched normal Wig. It worked well.

Best,
Joon
