### ISSUE TITLE
R installation broken

### ISSUE THREAD

**Issue by mheskett** [broadinstitute/ichorCNA#52]
Using R=3.6. 

If set up correctly your R recipe should find these dependencies and install them automatically. Also, the commit "--no-docs" is not found, so that is out of date.

> install_github("broadinstitute/ichorCNA")
Downloading GitHub repo broadinstitute/ichorCNA@master
Skipping 4 packages not available: HMMcopy, plyr, GenomicRanges, GenomeInfoDb
✔  checking for file ‘/tmp/Rtmp84DLC0/remotes3f0b339a480c/broadinstitute-ichorCNA-b32b215/DESCRIPTION’ (1.1s)
─  preparing ‘ichorCNA’:
✔  checking DESCRIPTION meta-information ...
   Warning: /tmp/Rtmpkp4yri/Rbuild807073702cc6/ichorCNA/man/ichorCNA-package.Rd:21: unexpected section header '\author'
   Warning: /tmp/Rtmpkp4yri/Rbuild807073702cc6/ichorCNA/man/ichorCNA-package.Rd:27: unexpected section header '\examples'
   Warning: /tmp/Rtmpkp4yri/Rbuild807073702cc6/ichorCNA/man/ichorCNA-package.Rd:35: unexpected END_OF_INPUT '
   '
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘ichorCNA/scripts’
─  building ‘ichorCNA_0.3.0.tar.gz’

ERROR: dependencies ‘HMMcopy’, ‘plyr’, ‘GenomicRanges’, ‘GenomeInfoDb’ are not available for package ‘ichorCNA’
* removing ‘/home/groups/Spellmandata/heskett/packages/envs/test123/lib/R/library/ichorCNA’
Error: Failed to install 'ichorCNA' from GitHub:

**Comment by gavinha** [comment]
Hi @mheskett 

Both https://cloud.r-project.org and https://cran.r-project.org/ are unresponsive for me. Perhaps wait until their servers are accessible. Installing dependencies is something that `install_github` handles and it seems by default it looks there.

Under [Installation](https://github.com/broadinstitute/ichorCNA/wiki/Installation), you can also try Option 2.

Hope this helps.

**Comment by jgarces02** [comment]
Hi @gavinha, 

I'm also trying to clone the github repository and I've problems too... any idea, please? Thanks!
```
Cloning into 'ichorCNA'...
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by mheskett** [comment]
I can confirm R-CRAN is responsive and get this error


```Downloading GitHub repo broadinstitute/ichorCNA@master
✔  checking for file ‘/tmp/RtmpjE9Oie/remotes154595ac465af/broadinstitute-ichorCNA-d91730c/DESCRIPTION’ (1.6s)
─  preparing ‘ichorCNA’:
✔  checking DESCRIPTION meta-information ...
   Warning: /tmp/RtmpdhRv0G/Rbuild18e885b9e3082/ichorCNA/man/ichorCNA-package.Rd:21: unexpected section header '\author'
   Warning: /tmp/RtmpdhRv0G/Rbuild18e885b9e3082/ichorCNA/man/ichorCNA-package.Rd:27: unexpected section header '\examples'
   Warning: /tmp/RtmpdhRv0G/Rbuild18e885b9e3082/ichorCNA/man/ichorCNA-package.Rd:35: unexpected END_OF_INPUT '
   '
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘ichorCNA/scripts’
─  building ‘ichorCNA_0.3.0.tar.gz’

* installing *source* package ‘ichorCNA’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) /tmp/Rtmp9Uo7M9/R.INSTALL18f3d1b76e86/ichorCNA/man/ichorCNA-package.Rd:21: unexpected section header '\author'
ERROR: installing Rd objects failed for package ‘ichorCNA’
* removing ‘/home/groups/Spellmandata/heskett/packages/envs/test123/lib/R/library/ichorCNA’
Error: Failed to install 'ichorCNA' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpjE9Oie/file15459101e3fe9/ichorCNA_0.3.0.tar.gz’ had non-zero exit status```

**Comment by jgarces02** [comment]
Perfect. If CRAN is the responsible, I guess installing it from Github would be possible but I've also problems... maybe I'm doing something wrong. Thanks again for your help!

**Comment by gavinha** [comment]
Hi @mheskett 

Please let me know if you are still having issues with the installation after the small change in the last commit.

Thanks,
Gavin

**Comment by jgarces02** [comment]
Solved! Thank you so much!
