### ISSUE TITLE
Error while running with GenomeInfoDb_1.20.0 installed from tar

### ISSUE THREAD

**Issue by patidarr** [broadinstitute/ichorCNA#58]
Hi,

I just installed ichorCNA and other dependencies but GenomeInfoDb is not available for R >3.6, I installed it from tar file, but now I am getting this error.

Could you please suggest some fix? 

```
Sorting by decreasing chromosome size
Correcting Tumour
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function 'seqinfo' for signature '"RangedData"'
Calls: loadReadCountsFromWig ... seqlevels -> seqlevels -> seqlevels -> seqinfo -> <Anonymous>
In addition: There were 13 warnings (use warnings() to see them)
Execution halted
```

Thanks,
Rajesh

**Comment by gavinha** [comment]
Hi @patidarr 

Are you using the latest [runIchorCNA.R](https://github.com/broadinstitute/ichorCNA/blob/master/scripts/runIchorCNA.R). Can you check in your version of the script that this line is there?

https://github.com/broadinstitute/ichorCNA/blob/bc89d52dc5a02e77094e5ca770c691494aca0911/scripts/runIchorCNA.R#L164

**Comment by patidarr** [comment]
Thanks @gavinha for the quick reply.

I was using script from 0.2.0 release. I just tried from the master branch and getting following error:
Removed 97 bins near centromeres.
Applying filter on data...
Correcting for GC bias...
Correcting for mappability bias...
Filtering low uniqueness regions with mappability score < 0.9
Removed 4 bins near centromeres.
Determining gender...Gender female
Error: RangedData objects are deprecated and the seqinfo() setter for
  RangedData objects is now defunct. Please migrate your code to use
  GRanges or GRangesList objects instead. See IMPORTANT NOTE in
  ?RangedData
In addition: Warning messages:
1: In dir.create(paste0(outDir, "/", id, "/"), recursive = TRUE) :
  'ichorCNA_OUT/134332-052-B' already exists
2: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
3: RangedData objects are deprecated. Please migrate your code to use
  GRanges or GRangesList objects instead. See IMPORTANT NOTE in
  ?RangedData
4: RangedData objects are deprecated. Please migrate your code to use
  GRanges or GRangesList objects instead. See IMPORTANT NOTE in
  ?RangedData
5: RangedData objects are deprecated. Please migrate your code to use
  GRanges or GRangesList objects instead. See IMPORTANT NOTE in
  ?RangedData
6: RangedData objects are deprecated. Please migrate your code to use
  GRanges or GRangesList objects instead. See IMPORTANT NOTE in
  ?RangedData
Execution halted

**Comment by gavinha** [comment]
Can you install ichorCNA directly from the master branch as well?

Also, can you show me the command you are using?  

Thanks,
Gavin

**Comment by patidarr** [comment]
Hi @gavinha,

Just figured out, that I should all the files from master as well. for 4.5X wgs, what settings would you recommend to call tumor fraction below 0.25%? 

Thanks,
Rajesh

**Comment by patidarr** [comment]
and I just got this error at the end:
runEM: Total elapsed time: 0.12min.
runViterbi: Segmenting and classifying
Total ULP-WGS HMM Runtime: 0.91 min.
Writing segments to ichorCNA_OUT/134332-052-B.seg
Outputting to bin-level results to ichorCNA_OUT/134332-052-B.cna.seg
Error in which(chrs == chrsNum[i]) : argument to 'which' is not logical
Calls: plotSolutions ... plotCorrectionGenomeWide -> getGenomeWidePositions -> which
Execution halted

**Comment by gavinha** [comment]
> and I just got this error at the end:
> runEM: Total elapsed time: 0.12min.
> runViterbi: Segmenting and classifying
> Total ULP-WGS HMM Runtime: 0.91 min.
> Writing segments to ichorCNA_OUT/134332-052-B.seg
> Outputting to bin-level results to ichorCNA_OUT/134332-052-B.cna.seg
> Error in which(chrs == chrsNum[i]) : argument to 'which' is not logical
> Calls: plotSolutions ... plotCorrectionGenomeWide -> getGenomeWidePositions -> which
> Execution halted

I've seen this error come up in other issues as well. I'll work on fixing this soon.

Thanks for bringing up these issues.
Best,
Gavin

**Comment by gavinha** [comment]
> Hi @gavinha,
> 
> Just figured out, that I should all the files from master as well. for 4.5X wgs, what settings would you recommend to call tumor fraction below 0.25%?
> 
> Thanks,
> Rajesh

I'm not sure if ichorCNA is able to provide the sensitivity for 0.25% at 4-5x WGS. In my own analysis, I was able to get down to that order of magnitude with about 40x WGS. 

That being said, you can try to set `--normal 0.995` and `--ploidy 2`. Also, keep with 1Mb bins. 

Please refer to [Parameter-tuning-and-settings](https://github.com/broadinstitute/ichorCNA/wiki/Parameter-tuning-and-settings) for more details.

**Comment by patidarr** [comment]
Thanks @gavinha for the suggestions, with my data I can get a prediction of 1% tumor fraction, only if there is a way to validate this :)

Thanks for developing the tool, will wait for the fix for the error I am getting.

Rajesh

**Comment by patidarr** [comment]
hi @gavinha, could you please let me know how may normal samples you used for creating the PON?

**Comment by patidarr** [comment]
Hi @gavinha, I have the latest code, (as of y'day) with the fix for plotting but I am still getting this error:
Total ULP-WGS HMM Runtime: 3.3 min.
Writing segments to Results_ichoCNA_MoChaBaseline/19-32079-004-M_cfNA_Qubit.seg
Outputting to bin-level results to Results_ichoCNA_MoChaBaseline/19-32079-004-M_cfNA_Qubit.cna.seg
Error in which(chrs == chrsNum[i]) : argument to 'which' is not logical
Calls: plotSolutions ... plotCorrectionGenomeWide -> getGenomeWidePositions -> which
Execution halted



Thanks,
Rajesh

**Comment by gavinha** [comment]
Hi @patidarr 

Can you please share with me (gha@fredhutch.org) the `.RData` file so that I can debug?  I am not able to reproduce this error with my runs. I'm starting to suspect it is related to R package versioning.

Thanks,
Gavin
