### ISSUE TITLE
Missing datadir argument option

### ISSUE THREAD

**Issue by simozacca** [broadinstitute/ichorCNA#6]
Dear authors,

I installed ichorCNA because I would like to run TitanCNA. Unfortunately, the snakemake file of Titcan expect that ichoCNA has some argument flags, such as "--datadir" that are missing from the script and are accepted, even if the documentation still report them as present. Could you please help me with this?

Best,
Simone

**Comment by gavinha** [comment]
Hi,

This is more of a problem with the snakemake from the TitanCNA workflow and not an issue with ichorCNA.  However, you are correct in that the snakemake file from TitanCNA that runs ichorCNA is out of date and will need to be updated there.

Best,
Gavin
