### ISSUE TITLE
Where is runIchorCNA.R installed to when using R CMD INSTALL?

### ISSUE THREAD

**Issue by callunity** [broadinstitute/ichorCNA#60]
Hello,

I tried to install ichorCNA using the following:
```
git clone git@github.com:broadinstitute/ichorCNA.git
cd ichorCNA
<install R dependencies>
R CMD INSTALL ichorCHA
```
This resulted in the following error message: `Warning: invalid pachage 'ichorCNA'. Error: ERROR: no packages specified`. 

I was able to bypass this error message by instead running:
```
cd ichorCNA
R CMD INSTALL .
```
The install completes, but the resulting R library installation doesn't contain the `runIchorCNA.R` script anywhere:
```
tree <R_install_dir>/lib/R/ichorCNA
├── DESCRIPTION
├── extdata
│   ├── cytoBand_hg38.txt
│   ├── (wig files)
├── help
│   ├── aliases.rds
│   ├── AnIndex
│   ├── ichorCNA.rdb
│   ├── ichorCNA.rdx
│   └── paths.rds
├── html
│   ├── 00Index.html
│   └── R.css
├── INDEX
├── LICENSE
├── Meta
│   ├── features.rds
│   ├── hsearch.rds
│   ├── links.rds
│   ├── nsInfo.rds
│   ├── package.rds
│   └── Rd.rds
├── NAMESPACE
└── R
    ├── ichorCNA
    ├── ichorCNA.rdb
    └── ichorCNA.rdx
```
(The R/ichorCNA file is not a copy of the runIchorCNA.R file)

Have I missed something for getting `runIchorCNA.R` installed?

Thank you,
Heather

**Comment by gavinha** [comment]
Hi @callunity 

The script and pipeline is contained in this repo. So if you cloned it, then you will have it.

Please refer to https://github.com/broadinstitute/ichorCNA/wiki/SnakeMake-pipeline-for-ichorCNA to see how to use the snakemake pipeline.

Best,
Gavin

**Comment by callunity** [comment]
Hi @gavinha , thanks for the speedy reply!

We don't use snakemake, and so would like to be able to install the `runIchorCNA.R` script for general use -- ideally as an R library. I had thought that `R CMD INSTALL ichorCNA` would allow us to do this, but it sounds like that's not the case. Can you recommend another option?

Thanks,
Heather

**Comment by gavinha** [comment]
Hi @callunity 

ichorCNA R package can be installed and used as a library. The `runIchorCNA.R` is a script that makes use of the ichorCNA library/package. Not sure if this answers your question.

Best,
Gavin

**Comment by callunity** [comment]
Hi @gavinha ,

It does, thanks!

Cheers,
Heather
