### ISSUE TITLE
Error in parse_args(parseobj)

### ISSUE THREAD

**Issue by vipuljain123** [broadinstitute/ichorCNA#61]
Hi
I am Getting error after running following command :+1: 

sudo Rscript /opt/installers/ichorCNA/scripts/runIchorCNA.R --id sample_id --WIG sample_id.wig --ploidy "c(2,3)" --normal "c(0.5,0.6,0.7,0.8,0.9)" --maxCN 5 -gcWig /opt/installers/ichorCNA/inst/extdata/gc_hg19_1000kb.wig --mapWig /opt/installers/ichorCNA/inst/extdata/map_hg19_1000kb.wig --centromere /opt/installers/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt --normalPanel /opt/installers/ichorCNA/inst/extdata/HD_ULP_PoN_1Mb_median_normAutosome_mapScoreFiltered_median.rds --includeHOMD False --chrs "c(1:22, \"X\")" --chrTrain "c(1:22)" --estimateNormal True --estimatePloidy True --estimateScPrevalence True --scStates "c(1,3)" --txnE 0.9999 --txnStrength 10000 --outDir ./

Error in parse_args(parseobj) : 
  Error in getopt(spec = spec, opt = args) : short flag "g" is invalid
Execution halted

**Comment by gavinha** [comment]
> sudo Rscript /opt/installers/ichorCNA/scripts/runIchorCNA.R --id sample_id --WIG sample_id.wig --ploidy "c(2,3)" --normal "c(0.5,0.6,0.7,0.8,0.9)" --maxCN 5 **-gcWig** /opt/installers/ichorCNA/inst/extdata/gc_hg19_1000kb.wig --mapWig /opt/installers/ichorCNA/inst/extdata/map_hg19_1000kb.wig --centromere /opt/installers/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt --normalPanel /opt/installers/ichorCNA/inst/extdata/HD_ULP_PoN_1Mb_median_normAutosome_mapScoreFiltered_median.rds --includeHOMD False --chrs "c(1:22, "X")" --chrTrain "c(1:22)" --estimateNormal True --estimatePloidy True --estimateScPrevalence True --scStates "c(1,3)" --txnE 0.9999 --txnStrength 10000 --outDir ./
> 
> Error in parse_args(parseobj) :
> Error in getopt(spec = spec, opt = args) : short flag "g" is invalid
> Execution halted

Hi @vipuljain123 

You need to use `--gcWig` for the argument flag. You only used `-gcWig` with one dash. 

Best,
Gavin
