### ISSUE TITLE
unable to find an inherited method for function ‘NSBS’ for signature ‘"CompressedIntegerList"

### ISSUE THREAD

**Issue by hw538** [broadinstitute/ichorCNA#72]
Removed 4 bins near centromeres.
Determining gender...Gender male
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘NSBS’ for signature ‘"CompressedIntegerList"’
Calls: normalizeByPanelOrMatchedNormal ... normalizeSingleBracketSubscript -> NSBS -> <Anonymous>
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

**Comment by hw538** [comment]
Hi, when I added panel of normal for ichorCNA, I got an error, would you have comments on how to solve it?

**Comment by hw538** [comment]
Problem solved, thx.

**Comment by rmvpaeme** [comment]
what was the solution?
