### ISSUE TITLE
Bug in plotting.R

### ISSUE THREAD

**Issue by biomorph** [broadinstitute/ichorCNA#8]
There is a bug in plotting.R that causes the runIchorCNA.R script to fail.
Offending call is on line 263
` plotChrLines(dataIn[,"chr"],coordEnd$chrBkpt,yrange)`
coordEnd isn't set unless it goes through the if condition on line 237.
Fix is to add an extra line after line 227
`coord <- getGenomeWidePositions(dataIn[,"chr"],dataIn[,"end"]) # existing line`
`coordEnd <- getGenomeWidePositions(dataIn[,"chr"],dataIn[,"end"]) # Added line`

**Comment by gavinha** [comment]
Hi,

Thank you for bringing this to our attention.  We will push a patch to GitHub as part of issue soon.
Just a quick question to help us replicate this since it only affects some users and not others.  

1) Are you using hg19 or hg38?  
2) Does your reference genome have chromosome naming convention "chr1" or "1"?

Thanks,
Gavin

**Comment by biomorph** [comment]
Julio, you might have to use the --libdir option to specify the path to your "fixed" runichor.R script location.
Gavin, I am using hg19 and my chromosomes are labeled 1:22, "X", "Y".
Thanks

**Comment by juliofinalet** [comment]
Hello biomorph and Gavin,

Thanks a lot for your comments.
I am also using hg19 and my chromosomes are labeled 1:22, "X", "Y".

The  fix proposed above for Plotting.R ( to add the extra line), combined a tiny change in runichorCNA.R solved my problem.  
In runichoCNA.R , around line 94, I simply fixed the value of libdir (libdir <-"/path/to/Plotting.R")

**Comment by jurhoades** [comment]
Sorry for the delay in response to this.  I believe the latest commit c1e41a84d52beb3faf53a2db80a14427fd95892c should fix this plotting bug.  After you reinstall the ichorCNA package you should be all set.  Please let us know if this continues to be a problem.
