### ISSUE TITLE
hg38 mappability file

### ISSUE THREAD

**Issue by leraman** [broadinstitute/ichorCNA#9]
Hi,

I noticed there are no hg38 mappability files included in /inst/extdata/. If no mappability file is provided, hg19 will be used from the ichorCNA package. Since I'm working on hg38, all my other arguments are set to hg38 files. Wouldn't this result in an incorrect normalization for mappability? Will these files for hg38 be uploaded in the future?

Thanks

**Comment by jurhoades** [comment]
Hi @leraman,

You are correct, there currently is no mappability file provided for hg38 and using the one for hg19 could cause issues.  We hope to add the hg38 mappability file to the package soon.  As the code stands now I don't believe that a mappability wig file is required, although the GC wig is.  If you don't specify a mappability file, it should just proceed with normalizing by GC only.  If you're using snakemake to run ichorCNA you should be able to modify the `config.yaml` file and set `ichorCNA_mapWig` to `NULL`.

**Comment by leraman** [comment]
Yes indeed, the stdout when running the software indeed told me no mappability correction will be executed. I was confused since the manual states:
```
--mapWig=MAPWIG
            Path to mappability score WIG file; if not provided then will use hg19 version from ichorCNA package. Default: [NULL]
```
Thanks!

**Comment by jurhoades** [comment]
Ahh that is confusing.  Thanks for pointing that out, I'll make sure to update that.
